### ISSUE TITLE
ValueError: keep_snps indices out of bounds

### ISSUE THREAD

**Issue by ldcato** [JonJala/mama#27]
Hi, excited about this software - congrats. 

Running on RedHat linux, within the virtualenv. 
I am running the latest version (i.e. followed your page advice and ran `git pull` to update). 
Tutorial data runs smoothly. 
I have this error using other data (see log attached below).

Summary of data:
4 ancestry groups. iid_ances_file and snp_ances_file formatted as per the wiki.
There are no duplicated IDs in the snp_ances_file or in the genotype data. 
There are "multi-allelic variants" i.e. variants at the same position but represented as sepeate variants (for example in:
VCF = 
#CHROM         POS             REF   ALT
2                       10304          A       T,C
PLINK Bfile = 
2                       10304          A       T
2                       10304          A       C
)
But they all have different RSIDs so I doubt this is causing the problem? 

One last addition: 
I am running `mama_ldscores.py` per chromosome but my `snp_ances_file` is just one entity chr1 -> chr22. Again, I am doubting this is causing the issue? 

Would greatly appreciate your help. I'm a bit stuck as to what the problem is. Thanks!
Liam

[chr1_EUR_AFR_SAR_THAI.log](https://github.com/JonJala/mama/files/6802319/chr1_EUR_AFR_SAR_THAI.log)

**Comment by ggoldman1** [comment]
Hey Liam,

Almost certainly the issue is that your genome-wide `snp_ances` file does not correspond to chromosome-level bim file. Having rsID's in your snp_ances file that aren't in your bim file will cause an indexing error. Can you make 22 of the `snp_ances` files, one for each chromosome, and let us know if that fixes it?

Grant

**Comment by ldcato** [comment]
Hi Grant! Ah thank you, sorry about that! 
Currently running - it's father than its ever gotten before! 
Thanks for your help!!

**Comment by ggoldman1** [comment]
Hey Liam, has this issue been resolved? 

Grant
