### ISSUE TITLE
Unable to install mama

### ISSUE THREAD

**Issue by Mahantesh-Biradar** [JonJala/mama#33]
git clone git@github.com:JonJala/mama.git
Cloning into 'mama'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by JonJala** [comment]
That command and repo information looks right at first glance.  Are you
able to clone other public repositories on GitHub?

**Comment by Mahantesh-Biradar** [comment]
Thanks! I was able to install it:)
